"""create pivot learn schema

Revision ID: 2f5e7d5a3818
Revises: 
Create Date: 2026-06-19 21:15:00.426362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2f5e7d5a3818'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('agent_name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_provider'), 'agent_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('input_type', sa.String(length=50), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('case_verdict', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('claim_embeddings',
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('embedding_model', sa.String(length=160), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claim_embeddings_embedding_model'), 'claim_embeddings', ['embedding_model'], unique=False)
    op.create_table('cost_logs',
    sa.Column('cost_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('cost_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('unit_name', sa.String(length=80), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cost_id')
    )
    op.create_index(op.f('ix_cost_logs_case_id'), 'cost_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_cost_logs_cost_type'), 'cost_logs', ['cost_type'], unique=False)
    op.create_index(op.f('ix_cost_logs_provider'), 'cost_logs', ['provider'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=True),
    sa.Column('query_id', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_span_start', sa.Integer(), nullable=True),
    sa.Column('evidence_span_end', sa.Integer(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=120), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('independence_group', sa.String(length=255), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('independence', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('specificity', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index('ix_evidence_claim_source', 'evidence', ['claim_id', 'source_id'], unique=False)
    op.create_index(op.f('ix_evidence_independence_group'), 'evidence', ['independence_group'], unique=False)
    op.create_index(op.f('ix_evidence_query_id'), 'evidence', ['query_id'], unique=False)
    op.create_index(op.f('ix_evidence_retrieval_method'), 'evidence', ['retrieval_method'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    op.create_table('evidence_embeddings',
    sa.Column('evidence_id', sa.String(length=160), nullable=False),
    sa.Column('embedding_model', sa.String(length=160), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_embeddings_embedding_model'), 'evidence_embeddings', ['embedding_model'], unique=False)
    op.create_table('graph_edges',
    sa.Column('edge_id', sa.String(length=180), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('src_node_id', sa.String(length=180), nullable=False),
    sa.Column('src_node_type', sa.String(length=80), nullable=False),
    sa.Column('dst_node_id', sa.String(length=180), nullable=False),
    sa.Column('dst_node_type', sa.String(length=80), nullable=False),
    sa.Column('edge_type', sa.String(length=100), nullable=False),
    sa.Column('edge_weight', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('edge_id'),
    sa.UniqueConstraint('src_node_id', 'dst_node_id', 'edge_type', name='uq_graph_edges_src_dst_type')
    )
    op.create_index(op.f('ix_graph_edges_case_id'), 'graph_edges', ['case_id'], unique=False)
    op.create_index('ix_graph_edges_case_type', 'graph_edges', ['case_id', 'edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_dst_node_id'), 'graph_edges', ['dst_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_dst_node_type'), 'graph_edges', ['dst_node_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_edge_type'), 'graph_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_src_node_id'), 'graph_edges', ['src_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_src_node_type'), 'graph_edges', ['src_node_type'], unique=False)
    op.create_table('llm_cache',
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('cache_namespace', sa.String(length=200), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_hash')
    )
    op.create_index(op.f('ix_llm_cache_cache_namespace'), 'llm_cache', ['cache_namespace'], unique=False)
    op.create_table('model_predictions',
    sa.Column('prediction_id', sa.String(length=180), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('features_version', sa.String(length=80), nullable=False),
    sa.Column('correctness_score', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('uncertainty_score', sa.Float(), nullable=False),
    sa.Column('support_score', sa.Float(), nullable=True),
    sa.Column('contradiction_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=80), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_model_predictions_case_id'), 'model_predictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_claim_id'), 'model_predictions', ['claim_id'], unique=False)
    op.create_index('ix_model_predictions_claim_model', 'model_predictions', ['claim_id', 'model_name'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_name'), 'model_predictions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_version'), 'model_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_predictions_verdict'), 'model_predictions', ['verdict'], unique=False)
    op.create_table('source_reliability',
    sa.Column('reliability_id', sa.String(length=220), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('claim_type', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=True),
    sa.Column('reliability_mean', sa.Float(), nullable=False),
    sa.Column('reliability_uncertainty', sa.Float(), nullable=False),
    sa.Column('num_observations', sa.Integer(), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('reliability_id'),
    sa.UniqueConstraint('domain', 'claim_type', 'topic', name='uq_source_reliability_domain_claim_type_topic')
    )
    op.create_index(op.f('ix_source_reliability_claim_type'), 'source_reliability', ['claim_type'], unique=False)
    op.create_index(op.f('ix_source_reliability_domain'), 'source_reliability', ['domain'], unique=False)
    op.create_index(op.f('ix_source_reliability_topic'), 'source_reliability', ['topic'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reliability_prior', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('stances',
    sa.Column('stance_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('evidence_id', sa.String(length=160), nullable=False),
    sa.Column('stance_label', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stance_id')
    )
    op.create_index(op.f('ix_stances_case_id'), 'stances', ['case_id'], unique=False)
    op.create_index('ix_stances_claim_evidence', 'stances', ['claim_id', 'evidence_id'], unique=False)
    op.create_index(op.f('ix_stances_claim_id'), 'stances', ['claim_id'], unique=False)
    op.create_index(op.f('ix_stances_evidence_id'), 'stances', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_stances_stance_label'), 'stances', ['stance_label'], unique=False)
    op.create_table('training_labels',
    sa.Column('label_id', sa.String(length=180), nullable=False),
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('label_source', sa.String(length=120), nullable=False),
    sa.Column('correctness_label', sa.Boolean(), nullable=True),
    sa.Column('verdict_label', sa.String(length=80), nullable=True),
    sa.Column('trust_label', sa.Float(), nullable=True),
    sa.Column('annotator_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_training_labels_case_id'), 'training_labels', ['case_id'], unique=False)
    op.create_index(op.f('ix_training_labels_claim_id'), 'training_labels', ['claim_id'], unique=False)
    op.create_index(op.f('ix_training_labels_label_source'), 'training_labels', ['label_source'], unique=False)
    op.create_index(op.f('ix_training_labels_verdict_label'), 'training_labels', ['verdict_label'], unique=False)
    op.create_table('verified_claims',
    sa.Column('normalized_claim_text', sa.Text(), nullable=False),
    sa.Column('claim_hash', sa.String(length=128), nullable=False),
    sa.Column('claim_type', sa.String(length=80), nullable=False),
    sa.Column('verdict', sa.String(length=80), nullable=False),
    sa.Column('correctness_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('freshness_policy', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('normalized_claim_text')
    )
    op.create_index(op.f('ix_verified_claims_claim_hash'), 'verified_claims', ['claim_hash'], unique=True)
    op.create_index(op.f('ix_verified_claims_claim_type'), 'verified_claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_verified_claims_expires_at'), 'verified_claims', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verified_claims_verdict'), 'verified_claims', ['verdict'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim_text', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('predicate', sa.Text(), nullable=True),
    sa.Column('object_value', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decomposition_confidence', sa.Float(), nullable=True),
    sa.Column('final_verdict', sa.String(length=80), nullable=True),
    sa.Column('correctness_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('uncertainty_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_final_verdict'), 'claims', ['final_verdict'], unique=False)
    op.create_index(op.f('ix_claims_normalized_claim_text'), 'claims', ['normalized_claim_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_normalized_claim_text'), table_name='claims')
    op.drop_index(op.f('ix_claims_final_verdict'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_verified_claims_verdict'), table_name='verified_claims')
    op.drop_index(op.f('ix_verified_claims_expires_at'), table_name='verified_claims')
    op.drop_index(op.f('ix_verified_claims_claim_type'), table_name='verified_claims')
    op.drop_index(op.f('ix_verified_claims_claim_hash'), table_name='verified_claims')
    op.drop_table('verified_claims')
    op.drop_index(op.f('ix_training_labels_verdict_label'), table_name='training_labels')
    op.drop_index(op.f('ix_training_labels_label_source'), table_name='training_labels')
    op.drop_index(op.f('ix_training_labels_claim_id'), table_name='training_labels')
    op.drop_index(op.f('ix_training_labels_case_id'), table_name='training_labels')
    op.drop_table('training_labels')
    op.drop_index(op.f('ix_stances_stance_label'), table_name='stances')
    op.drop_index(op.f('ix_stances_evidence_id'), table_name='stances')
    op.drop_index(op.f('ix_stances_claim_id'), table_name='stances')
    op.drop_index('ix_stances_claim_evidence', table_name='stances')
    op.drop_index(op.f('ix_stances_case_id'), table_name='stances')
    op.drop_table('stances')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_source_reliability_topic'), table_name='source_reliability')
    op.drop_index(op.f('ix_source_reliability_domain'), table_name='source_reliability')
    op.drop_index(op.f('ix_source_reliability_claim_type'), table_name='source_reliability')
    op.drop_table('source_reliability')
    op.drop_index(op.f('ix_model_predictions_verdict'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_version'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_name'), table_name='model_predictions')
    op.drop_index('ix_model_predictions_claim_model', table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_claim_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_case_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_llm_cache_cache_namespace'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_graph_edges_src_node_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_src_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_edge_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_dst_node_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_dst_node_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_case_type', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_case_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_evidence_embeddings_embedding_model'), table_name='evidence_embeddings')
    op.drop_table('evidence_embeddings')
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_retrieval_method'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_query_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_independence_group'), table_name='evidence')
    op.drop_index('ix_evidence_claim_source', table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_cost_logs_provider'), table_name='cost_logs')
    op.drop_index(op.f('ix_cost_logs_cost_type'), table_name='cost_logs')
    op.drop_index(op.f('ix_cost_logs_case_id'), table_name='cost_logs')
    op.drop_table('cost_logs')
    op.drop_index(op.f('ix_claim_embeddings_embedding_model'), table_name='claim_embeddings')
    op.drop_table('claim_embeddings')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_provider'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
