from pydantic import BaseModel

from app.agents.base import Agent
from app.core.constants import VerdictLabel
from app.schemas.agent import AtomicClaim, EvidenceItem, PivotVerdict
from app.schemas.api import ClaimFinding, InvestigationReport


class ReportAgentInput(BaseModel):
    title: str
    input_text: str
    case_verdict: VerdictLabel | None
    confidence: float | None

    claims: list[AtomicClaim]
    evidence: list[EvidenceItem]
    verdicts: list[PivotVerdict]


class ReportAgent(Agent[ReportAgentInput, InvestigationReport]):
    name = "report_agent"

    def run(self, input_data: ReportAgentInput) -> InvestigationReport:
        claim_findings = self._build_claim_findings(input_data)
        key_evidence = self._build_key_evidence(input_data.evidence)
        remaining_uncertainty = self._build_remaining_uncertainty(input_data.verdicts)
        summary = self._build_summary(input_data)

        memo_markdown = self._build_memo_markdown(
            title=input_data.title,
            verdict=input_data.case_verdict,
            confidence=input_data.confidence,
            summary=summary,
            claim_findings=claim_findings,
            key_evidence=key_evidence,
            remaining_uncertainty=remaining_uncertainty,
        )

        return InvestigationReport(
            title=input_data.title,
            verdict=input_data.case_verdict,
            confidence=input_data.confidence,
            summary=summary,
            claim_findings=claim_findings,
            key_evidence=key_evidence,
            remaining_uncertainty=remaining_uncertainty,
            memo_markdown=memo_markdown,
        )

    def _build_claim_findings(
        self,
        input_data: ReportAgentInput,
    ) -> list[ClaimFinding]:
        claims_by_id = {claim.claim_id: claim for claim in input_data.claims}

        findings: list[ClaimFinding] = []
        for verdict in input_data.verdicts:
            claim = claims_by_id.get(verdict.claim_id)
            if claim is None:
                continue

            findings.append(
                ClaimFinding(
                    claim_id=claim.claim_id,
                    claim_text=claim.claim_text,
                    verdict=verdict.verdict,
                    confidence=verdict.confidence,
                    reason=verdict.reason,
                )
            )

        return findings

    def _build_key_evidence(self, evidence_items: list[EvidenceItem]) -> list[str]:
        if not evidence_items:
            return ["No evidence was collected."]

        return [
            f"{item.title or 'Untitled evidence'} — {item.evidence_text}"
            for item in evidence_items[:5]
        ]

    def _build_remaining_uncertainty(
        self,
        verdicts: list[PivotVerdict],
    ) -> list[str]:
        uncertainty: list[str] = []

        for verdict in verdicts:
            if verdict.verdict in {
                VerdictLabel.PARTIALLY_SUPPORTED,
                VerdictLabel.UNVERIFIABLE,
                VerdictLabel.CONTESTED,
            }:
                uncertainty.append(
                    f"{verdict.claim_id}: {verdict.reason}"
                )

        if not uncertainty:
            uncertainty.append("No major uncertainty was detected in this mock investigation.")

        return uncertainty

    def _build_summary(self, input_data: ReportAgentInput) -> str:
        verdict_text = input_data.case_verdict or "unknown"
        confidence_text = (
            f"{input_data.confidence:.2f}"
            if input_data.confidence is not None
            else "unknown"
        )

        return (
            f"The investigation completed with a case-level verdict of "
            f"{verdict_text} and confidence {confidence_text}. "
            f"This result is generated by the current mock investigation pipeline."
        )

    def _build_memo_markdown(
        self,
        title: str,
        verdict: VerdictLabel | None,
        confidence: float | None,
        summary: str,
        claim_findings: list[ClaimFinding],
        key_evidence: list[str],
        remaining_uncertainty: list[str],
    ) -> str:
        confidence_text = f"{confidence:.2f}" if confidence is not None else "unknown"

        claim_lines = "\n".join(
            [
                (
                    f"- **{finding.verdict}** "
                    f"({finding.confidence:.2f}): {finding.claim_text}\n"
                    f"  - Reason: {finding.reason}"
                )
                for finding in claim_findings
            ]
        )

        evidence_lines = "\n".join([f"- {item}" for item in key_evidence])
        uncertainty_lines = "\n".join([f"- {item}" for item in remaining_uncertainty])

        return f"""# Investigation Report: {title}

## Verdict

**{verdict or "unknown"}**

Confidence: **{confidence_text}**

## Summary

{summary}

## Claim-Level Findings

{claim_lines}

## Key Evidence

{evidence_lines}

## Remaining Uncertainty

{uncertainty_lines}
"""
